### ISSUE TITLE
Sign in (frontend)

### ISSUE THREAD

**Issue by S-i-d-V** [luweglarz/ft_transcendence#14]
## Description of the feature:
Create the sign up page with a button to sign up wiith a 42 account.

## Description of the solution:
A simple page with a button with a click action that will communicate with the 42Oauth API.
(Not sure for the moment)Then send the response of the API to the back end.

## Tasks:
- [x] Structure the HTML/CSS Template.
- [ ] Communicate with 42Oauth API.
- [ ] (?) Treat the response of the 42Oauth API
