### ISSUE TITLE
Register (frontend)

### ISSUE THREAD

**Issue by S-i-d-V** [luweglarz/ft_transcendence#15]
## Description of the feature:
Create the register page accessible once the the user is authentified.
This page allow the user to upload an avatar, choose an unique user name and enable or not the 2FA Authentication.

## Description of the solution:
A simple page with 3 elements:
- An clickable avatar that allow the user to upload a custom one. If none is uploaded, there must be a default one.
- A field  to choose a unique username.
- A checkbox to enable 2FA authentication (email). Open a email field if enabled.
- A submit button.

##Tasks:
- [ ] Structure the HTML/CSS Template.
- [ ] Allowing user to upload an image file.
- [ ] Handle errors (Bad avatar format, Not unique username, Invalid mail).
- [ ] Submit the user informations to the back-end or the database.
