### ISSUE TITLE
Implement database

### ISSUE THREAD

**Issue by ecogest** [luweglarz/ft_transcendence#3]
**Is your feature request related to a problem? Please describe.**
The postgres db must be accessible from the backend.

**Describe the solution you'd like**
Use [prisma](https://www.prisma.io/docs/) to setup and access our database.

**Describe alternatives you've considered**
typeorm

**Tasks**
- [x] Init prisma
- [x] Create a minimalistic User model
- [x] Integrate database and prisma's tools with the root's docker-compose
- [x] unit-test query on database
- [x] integrate database unit-testing with github workflow
- [ ] add a bit of documentation
