### ISSUE TITLE
Authentication roadmap

### ISSUE THREAD

**Issue by ecogest** [luweglarz/ft_transcendence#50]
### Todo

- [ ] display and submit the profile picture uploaded on signup
- [ ] cache the profile picture?
- [ ] Front: error handling (e.g. custom messages if username taken or if signup/signin fails)
- [ ] Unit/integration-testing of the auth module
- [ ] automatically refresh the access token
- [ ] 2FA
