### ISSUE TITLE
Refresh access tokens

### ISSUE THREAD

**Issue by ecogest** [luweglarz/ft_transcendence#98]
Automatically refresh the access token

##### Tasks:
- [x] backend: methods to generate, compare and clear refresh token
- [x] front: store refresh token alongside access token
- [x] front: if access token is stale, request a fresh pair of tokens

Relates to #50
